#lang racket
(define (calculate-sum x n)
   (define (sum result counter)
        (if (zero? counter)
           (add1 result)
           (sum (+ result (expt x counter)) (sub1 counter))
            )
     )
    (sum 0 n)
  )
(= (calculate-sum 5 0) 1)
(= (calculate-sum 5 1) 6)
(= (calculate-sum 10 1) 11)
(= (calculate-sum 1 11) 12)
(= (calculate-sum 2 11) 4095)
(= (calculate-sum 3 3) 40);my test
